# Generated by Django 5.0.1 on 2024-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Category', models.TextField(max_length=100)),
                ('Job_Level', models.TextField(max_length=100)),
                ('Job_Type', models.TextField(max_length=100)),
                ('Job_Location', models.TextField(max_length=100)),
                ('Job_Vacanys', models.IntegerField()),
                ('Job_Salary', models.IntegerField()),
                ('Job_Deadline', models.DateTimeField()),
                ('Job_Educationlevel', models.TextField(max_length=100)),
                ('Job_Experience', models.TextField(max_length=100)),
            ],
        ),
    ]
