# Generated by Django 5.0.1 on 2024-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_information',
            name='Job_Category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job_information',
            name='Job_Educationlevel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job_information',
            name='Job_Experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job_information',
            name='Job_Level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job_information',
            name='Job_Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job_information',
            name='Job_Type',
            field=models.CharField(max_length=100),
        ),
    ]
