# Generated by Django 5.0.1 on 2024-01-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0002_alter_job_information_job_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_information1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Category1', models.CharField(max_length=100)),
                ('Job_Level1', models.CharField(max_length=100)),
                ('Job_Type1', models.CharField(max_length=100)),
                ('Job_Location1', models.CharField(max_length=100)),
                ('Job_Vacanys1', models.IntegerField()),
                ('Job_Salary1', models.IntegerField()),
                ('Job_Deadline1', models.DateTimeField()),
                ('Job_Educationlevel1', models.CharField(max_length=100)),
                ('Job_Experience1', models.CharField(max_length=100)),
                ('Job_Skills1', models.CharField(max_length=100)),
            ],
        ),
    ]
