# Generated by Django 5.0.1 on 2024-02-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0004_contactus_job_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_show',
            old_name='Job_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job_show',
            old_name='Job_Title',
            new_name='title',
        ),
    ]
