# Generated by Django 5.0.1 on 2024-02-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0005_rename_job_description_job_show_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_show',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='job_show',
            old_name='title',
            new_name='Title',
        ),
    ]
