# Generated by Django 5.0.1 on 2024-02-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0006_rename_description_job_show_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_show',
            old_name='Description',
            new_name='Job_Description',
        ),
        migrations.RenameField(
            model_name='job_show',
            old_name='Title',
            new_name='Job_Title',
        ),
    ]
