# Generated by Django 5.0.1 on 2024-02-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0007_rename_description_job_show_job_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_show',
            new_name='Jobshow',
        ),
    ]
