# Generated by Django 5.0.2 on 2024-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0008_rename_job_show_jobshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='addjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=100)),
                ('jdescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobshow',
        ),
    ]
