# Generated by Django 5.0.2 on 2024-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0010_addjobs_jcompany_addjobs_jimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjobs',
            name='jimage',
            field=models.ImageField(default='', upload_to='home1/allimages'),
        ),
    ]
